### PR TITLE
Decode a Morse code message

### PR DESCRIPTION
**Pull request by PrantoshB**
## Hello There 👋

Hello

In this branch, I and my coding partner @tanveerisonline have:
- Created a method in ruby that decodes morse code
- Fixed Linters Errors
- Followed Git and GitHub flows

### Thanks 🍻

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented, and adhere(s) to the following standard(s):
- [ ] All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the _FAQ_ section is optional.
- [ ]  The _Future Features_ section of your ReadMe includes 1-3 potential features to be added later. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by PrantoshB** [comment]
Hello @rloterh can you guide us what to write in the Future Features section?
As it's a learning project, so I can't think of any features to add in future. Kindly help,

Regards,
Prantosh

**Review by DammyShittu — APPROVED** [review]
Hi @PrantoshB and @tanveerisonline,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PrantoshB** [comment]
Thanks @DammyShittu for reviewing our project.

Have a good day 💐

**Comment by rloterh** [comment]
> Hello @rloterh can you guide us what to write in the Future Features section? As it's a learning project, so I can't think of any features to add in future. Kindly help,
> 
> Regards, Prantosh

Hi @PrantoshB 

As developers, we always need to think of ways of being innovative, no matter how small or basic a project may be 😉 

Of course, you can add a..
 * how to do the reverse, thus decode a text,
 * unit test,
and so much more we can think about! 😃

**Pull request merged**
